name: 'Update Asana Tasks'
description: 'Manage versions via git tags'
inputs:
  is-review:
    default: false
  asana-pat:
    required: true
  github-token:
    required: true
  github-token:
    required: true
  slack-bot-token:
    required: false
  slack-bot-channel-id:
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'